index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index

user/login:
    path: /user/login
    methods: GET
    controller: App\Controller\UserController::signUp

login:
    path: /login
    methods: POST
    controller: App\Controller\UserController::login

room:
    path: /room
    methods: GET
    controller: App\Controller\GameController::selectRoom

lobby:
    path: /lobby
    methods: GET
    controller: App\Controller\GameController::lobby

menu:
    path: /menu
    methods: GET
    controller: App\Controller\GameController::showMenu

single:
    path: /single
    methods: GET
    controller: App\Controller\GameController::single

game:
    path: /game
    methods: GET
    controller: App\Controller\GameController::start

reset:
    path: /reset
    methods: GET
    controller: App\Controller\GameController::reset

info:
    path: /game/info
    controller: App\Controller\GameController::getGameInfo

move:
    path: /snake/move
    methods: POST
    controller: App\Controller\GameController::setSnakeDirection

score:
    path: /get/score
    methods: GET
    controller: App\Controller\UserController::getScore