index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index

user/login:
    path: /user/login
    methods: GET
    controller: App\Controller\UserController::signUp

login:
    path: /login
    methods: POST
    controller: App\Controller\UserController::login

menu:
    path: /menu
    methods: GET
    controller: App\Controller\GameController::showMenu

room:
    path: /room
    methods: GET
    controller: App\Controller\GameController::multiplayer

single:
    path: /single
    methods: GET
    controller: App\Controller\GameController::single

score:
    path: /get/score/{name}
    methods: GET
    controller: App\Controller\UserController::getScore