index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index

login:
    path: login
    methods: GET
    controller: App\Controller\UserController::login

settings:
    path: /game/start
    methods: POST
    controller: App\Controller\GameController::start

info:
    path: /game/info
    controller: App\Controller\GameController::getGameInfo

move:
    path: /snake/move
    methods: POST
    controller: App\Controller\GameController::setSnakeDirection
