index:
    path: /
    methods: GET
    controller: App\Controller\UserController::index

user/login:
    path: /user/login
    methods: GET
    controller: App\Controller\UserController::signUp

login:
    path: /login
    methods: POST
    controller: App\Controller\UserController::login

menu:
    path: /menu
    methods: GET
    controller: App\Controller\GameController::showMenu

game:
    path: /game
    methods: GET
    controller: App\Controller\GameController::start

info:
    path: /game/info
    controller: App\Controller\GameController::getGameInfo

move:
    path: /snake/move
    methods: POST
    controller: App\Controller\GameController::setSnakeDirection
