index:
    path: /game/start
    methods: POST
    controller: App\Controller\GameController::start

info:
    path: /game/info
    controller: App\Controller\GameController::getGameInfo

move:
    path: /snake/move
    methods: POST
    controller: App\Controller\GameController::setSnakeDirection
